Repository dalbitresb12/databases-report, pull requests merged in 2021-11, with the labels that each got.

#2 Removed lua compiler and scripts
  .vscode/extensions.json
  .vscode/settings.json
  src/main.tex
  src/parse_xml.lua
  src/upcreport.cls
  src/vertabelo.sty
Labels: bug

#1 Added CI with GitHub Actions
  .github/release.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  .vscode/extensions.json
  .vscode/settings.json
Labels: enhancement

#4 Implemented enumeratedtable package
  .vscode/settings.json
  src/enumeratedtable.sty
Labels: enhancement

#3 Added babel and T1's fontenc for spanish support
  src/main.tex
  src/upcreport.cls
Labels: enhancement

#6 Implemented subfiles and added content from doc
  .vscode/settings.json
  src/main.tex
  src/sections/business-about.tex
  src/sections/database-metadata.tex
  src/sections/detailed-tables.tex
Labels: enhancement, content

#5 Created Vertabelo database environment
  .vscode/settings.json
  src/main.tex
  src/vertabelo.sty
Labels: enhancement

#8 Added document sections for future filling
  src/sections/database-metadata.tex
Labels: content

#7 Added vertabelo-latex project
  .github/workflows/latex.yml
  .github/workflows/update.yml
  .github/workflows/vertabelo-latex.yml
  lib/.babelrc
  lib/.env.example
  lib/.eslintignore
  lib/.eslintrc.js
  lib/.gitignore
  lib/gulpfile.esm.js
  lib/package.json
  lib/src/index.ts
  lib/src/utils/fetcher.ts
  lib/src/utils/package.ts
  lib/src/utils/parser.ts
  lib/src/utils/transform.ts
  lib/tsconfig.json
  lib/yarn.lock
Labels: enhancement

#15 Added generation of attribute tables
  lib/src/index.ts
  lib/src/utils/parser.ts
  lib/src/utils/transform.ts
Labels: enhancement

#11 Added `attrtables` environment
  src/sections/attribute-tables.tex
  src/sections/database-metadata.tex
  src/vertabelo.sty
Labels: enhancement

#14 Added utils used to convert Word tables to XML
  utils/.gitignore
  utils/input.txt
  utils/input.xml
  utils/json-to-xml.js
  utils/output.json
  utils/output.xml
  utils/package.json
  utils/word-to-json.js
  utils/yarn.lock
Labels: enhancement

#16 Add `out/` folder to cleanup script
  lib/package.json
Labels: bug

#17 Added check for model version
  lib/src/utils/parser.ts
  lib/src/utils/transform.ts
Labels: enhancement

#18 Updated vertabelo description
  exports/coursera_data_model.xml
Labels: content

#19 Updated vertabelo descriptions
  exports/coursera_data_model.xml
Labels: content

#20 Updated vertabelo descriptions
  exports/coursera_data_model.xml
Labels: content

#22 Fixed description not being parsed
  lib/src/utils/transform.ts
Labels: bug

#23 Fixed FK descriptions
  exports/coursera_data_model.xml
Labels: bug

#24 Added back contents missing from old Word document
  .vscode/settings.json
  src/images/database-diagram.png
  src/images/procesos-principales.png
  src/main.tex
  src/sections/database-metadata.tex
  src/sections/normalization.tex
Labels: content

#28 Updated release workflow
  .github/workflows/release.yml
  .vscode/settings.json
  exports/README.md
Labels: chore

#29 Updated README.md
  README.md
Labels: chore

#30 Fixed update workflow errors
  .github/workflows/release.yml
Labels: bug

#31 Added Franco Galindo Queries
  sql/franco-galindo.sql
Labels: chore

#33 Added Jhonel Rios queries
  sql/jhonel-rios.sql
Labels: chore

#32 Added Angel Meneses queries
  sql/angel-meneses.sql
Labels: chore

#34 Minor fixes to queries
  sql/diego-albitres.sql
Labels: bug

#35 add Stefano Solis querys
  sql/stefano-solis.sql
Labels: chore

#36 Fixed franco-galindo
  sql/franco-galindo.sql
Labels: chore

#37 Added important comment
  sql/angel-meneses.sql
Labels: documentation
